name: flutter_login
description: A login widget with login/signup functionalities to help speed up development
version: 4.1.0
homepage: https://github.com/NearHuscarl/flutter_login

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  provider: ^6.0.1
  another_transformer_page_view: ^2.0.0
  another_flushbar: ^1.10.29
  sign_in_button: ^3.0.0

  # flutter_test from sdk depends on quiver
  quiver: ^3.0.1
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/ecorp.png