name: flutter_login
description: A login widget with login/signup functionalities to help speed up development
version: 4.1.1
repository: https://github.com/NearHuscarl/flutter_login

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  another_flushbar: ^1.10.29
  another_transformer_page_view: ^2.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  intl_phone_number_input: ^0.7.2
  phone_numbers_parser: ^7.0.0+1
  provider: ^6.0.1
  quiver: ^3.0.1
  sign_in_button: ^3.0.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  mockito: ^5.0.16


flutter:
  uses-material-design: true
  assets:
    - assets/images/ecorp.png