name: ğŸ“ Code Quality

on: [push, pull_request]

defaults:
  run:
    shell: bash

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  analysis:
    name: ğŸ” Analysis
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v5

      - name: âš¡ Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: ğŸ” Flutter Version Info
        run: flutter doctor -v

      - name: ğŸ“¦ Cache Pub Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: ğŸ”§ Bootstrap Workspace
        run: flutter pub get

      - name: âœ… Lint Code
        run: flutter analyze

  formatting:
    name: ğŸ¨ Formatting
    needs: analysis  # This makes formatting start after analysis is complete
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v5

      - name: âš¡ Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: ğŸ”§ Bootstrap Workspace
        run: flutter pub get

      - name: ğŸ¯ Check Code Formatting
        run: dart format --set-exit-if-changed .

  test:
    name: Testing
    needs: formatting
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v5

      - name: âš¡ Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: ğŸ” Flutter Version Info
        run: flutter doctor -v

      - name: ğŸ“¦ Cache Pub Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: ğŸ”§ Bootstrap Workspace
        run: flutter pub get

      - name: Test
        run: flutter test
